#!/usr/bin/env python3
"""Emit DataHub-ingestible metadata from the catalog index.

Turns the catalog-index into DataHub MetadataChangeProposals (file-source form) so
that when a DataHub GMS is present, `datahub ingest -c datahub/recipe.yml` loads:
  - one Dataset entity per catalog dataset (datasetProperties),
  - one GlossaryTerm per glossary entry (glossaryTermInfo with the definition)
    + glossaryRelatedTerms for the linked terms.
This is the "backing store: DataHub" wire that was previously only a thesis. It is
file-based and requires a running GMS to load; the recipe + MCPs are emitted here.

Stdlib only. Outputs datahub/catalog-mcps.json and datahub/recipe.yml.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IDX = ROOT / "catalog-index"
OUT = ROOT / "datahub"
PLATFORM = "urn:li:dataPlatform:socioprophet-catalog"


def _term_urn(name: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]", "_", name)[:120]
    return f"urn:li:glossaryTerm:socioprophet.{slug}"


def mcp(entity_type, urn, aspect_name, aspect):
    return {"entityType": entity_type, "entityUrn": urn,
            "changeType": "UPSERT", "aspectName": aspect_name,
            "aspect": {"value": json.dumps(aspect), "contentType": "application/json"}}


def emit() -> int:
    if not (IDX / "index.json").exists():
        print("ERR: run tools/build_catalog_index.py first", file=sys.stderr)
        return 2
    OUT.mkdir(exist_ok=True)
    idx = json.loads((IDX / "index.json").read_text())
    mcps = []

    # Dataset entities (one per catalog dataset)
    for r in idx["registry"]:
        urn = f"urn:li:dataset:({PLATFORM},{r['id'] or r['dataset']},PROD)"
        mcps.append(mcp("dataset", urn, "datasetProperties", {
            "name": r["dataset"], "qualifiedName": r.get("id"),
            "customProperties": {"version": str(r.get("version")), "assets": str(r["assets"]),
                                 "sources": str(r.get("sources"))},
            "description": f"SocioProphet catalog dataset {r.get('id')} ({r['assets']} assets)."}))

    # GlossaryTerms (definitions + related terms)
    seen = set()
    for g in (json.loads(l) for l in (IDX / "glossary.jsonl").read_text().splitlines() if l.strip()):
        name = g.get("name")
        if not name or not g.get("definition"):
            continue
        urn = _term_urn(name)
        if urn in seen:
            continue
        seen.add(urn)
        mcps.append(mcp("glossaryTerm", urn, "glossaryTermInfo", {
            "name": name, "definition": g["definition"], "termSource": "INTERNAL",
            "sourceRef": g.get("source")}))
        related = [_term_urn(t) for t in (g.get("related_terms") or [])[:25] if t]
        if related:
            mcps.append(mcp("glossaryTerm", urn, "glossaryRelatedTerms",
                            {"relatedTerms": related}))

    (OUT / "catalog-mcps.json").write_text(json.dumps(mcps, indent=1) + "\n", encoding="utf-8")
    (OUT / "recipe.yml").write_text(
        "# DataHub file-source ingestion recipe for the SocioProphet asset catalog.\n"
        "# Requires a running DataHub GMS. Load with: datahub ingest -c datahub/recipe.yml\n"
        "# The MCPs are regenerated by tools/emit_datahub.py from catalog-index/.\n"
        "source:\n"
        "  type: file\n"
        "  config:\n"
        "    path: ./datahub/catalog-mcps.json\n"
        "sink:\n"
        "  type: datahub-rest\n"
        "  config:\n"
        "    server: ${DATAHUB_GMS_URL:-http://localhost:8080}\n"
        "    token: ${DATAHUB_GMS_TOKEN:-}\n", encoding="utf-8")
    print(f"OK: emitted {len(mcps)} DataHub MCPs ({len(seen)} glossary terms + "
          f"{idx['datasets']} datasets) -> {OUT}/catalog-mcps.json (+ recipe.yml)")
    return 0


if __name__ == "__main__":
    sys.exit(emit())
